### ISSUE TITLE
PR #42, problemas

### ISSUE THREAD

**Issue by SamuelLimaCap** [SamuelLimaCap/api-agendamento-banca#47]
- [x] Quando vocẽ tenta adicionar/remover um usuário em uma banca que não existe, é retornado a mensagem que o usuário não foi encontrado. Precisa retornar que a banca não existe.

![image](https://user-images.githubusercontent.com/67354841/174456382-f1b5139d-37cf-4b8f-a3f1-4faa909ad7a8.png)

- [x] Quando não cria um array para o admin da banca, não é mostrado na mensagem qual atributo está faltando ou que os atributos estão incorretos

![image](https://user-images.githubusercontent.com/67354841/174456510-9c877d1b-7fde-4773-9702-83e1ce7c157b.png)

- [x] No Get ALL AGENDAMENTOS e no GET AGENDAMENTO BY ID, nao está mostrando quem é o admin da banca.

![image](https://user-images.githubusercontent.com/67354841/174456553-43c151fc-0951-4a89-ab8f-789c959af6bf.png)

- [x] Ao tentar cadastrar/remover um admin que nao existe na banca, especificar que o usuário nao foi encontrado nessa banac

![image](https://user-images.githubusercontent.com/67354841/174456606-f642fef0-496c-4893-b753-9dd521a69f27.png)

- [x] Ao dar update na banca, é resetado os admins. Mesmo passando a lista de admins, TODOS os admins da banca estão sendo retirados. Precisa fazer a validação dos admins na rota de "update" também.
![image](https://user-images.githubusercontent.com/67354841/174456800-ea2f164c-2e37-4fa1-a2c2-ae816afaf882.png)

- [x] Ao dar update na banca, a restrição de data está impedindo de atualizar a própria banca. Se há SOMENTE 1 banca cadastrada e eu tento modificar o horário dela, eu preciso colocar 1 hora a mais ou 1 hora a menos, senão ele não aceita dizendo que há conflito de horarios.

**Comment by SamuelLimaCap** [comment]
Os usuários criados foram estes:

```
@Bean
    CommandLineRunner run(UserRepository userRepository, PermissaoRepository permissaoRepository) {
        return args -> {

            permissaoRepository.saveAll(getAllPermissaoFromPermissaoEnum());
            Permissao permissaoAdmin = permissaoRepository.getByCodeName(PermissaoEnum.ADMIN.name());
            Permissao permissaoUsuario = permissaoRepository.getByCodeName(PermissaoEnum.USUARIO.name());

            List<Usuario> usuarios = List.of(
                    createCommonUserByEmailAndPassword("admin@admin.com", "admin", List.of(permissaoAdmin)),
                    createCommonUserByEmailAndPassword("usuario@usuario.com", "usuario", List.of(permissaoUsuario)),
                    createCommonUserByEmailAndPassword("samueldelimapessoal@gmail.com", "samueldelimapessoal", List.of(permissaoUsuario)),
                    createCommonUserByEmailAndPassword("caiopaiva@gmail.com", "caiopaiva", List.of(permissaoUsuario)),
                    createCommonUserByEmailAndPassword("giovani@ifsp", "giovani", List.of(permissaoUsuario))
            );

            userRepository.saveAll(usuarios);
        };
    }

    private Usuario createCommonUserByEmailAndPassword(String email, String password, List<Permissao> permissoes) {
        return new Usuario(null, email, passwordEncoder().encode(password), true, permissoes);
    }
```

**Comment by CaioPaiva1911** [comment]
Faltante somente implementar os dois últimos tópicos que vou verificar amanhã!

**Comment by CaioPaiva1911** [comment]
Só falta o último ponto agora, vou matar amanhã, sou humano e mereço dormir.

**Comment by CaioPaiva1911** [comment]
Implementado validações e outros pontos descritos no erro, validar por favor valeu

**Comment by CaioPaiva1911** [comment]
PR que está aberto contendo o novo commit

**Comment by SamuelLimaCap** [comment]
Fix on #42
